@startuml

== 初始化流程 ==

Application -> LeakCanary: install()
LeakCanary -> RefWatcher: androidWatcher()
RefWatcher -> AndroidWatchExecutor: new AndroidWatcherExecutor()
RefWatcher -> AndroidHeapDumper: new AndroidHeapDumper()
RefWatcher -> ServiceHeapDumpListener: new ServiceHeapDumpListener()
RefWatcher -> LeakCanary: refWatcher
LeakCanary -> LeakCanary: ActivityRefWatcher.installOnIcsPlus()
LeakCanary -> Application: refWatcher

== 检查泄漏流程 ==

Application -> RefWatcher: watch()
RefWatcher -> AndroidWatchExecutor: ensureGone(KeyedWeakReference)
AndroidWatchExecutor --> AndroidHeapDumper: dumpHeap()
AndroidWatchExecutor --> ServiceHeapDumpListener: analyze()
ServiceHeapDumpListener --> HeapAnalyzerService: runAnalysis()
note right: 通过 HeapAnalyzer 来从 HPROF 文件里检查内存泄漏
HeapAnalyzerService --> DisplayLeakService: sendResultToListener()
note right: 通过 logcat 打印内存泄漏信息\n在设备通知栏显示内存泄漏信息

== 当 Activity 退出时，自动检查 Activity 泄漏情况 ==

-> Application: onActivityDestroyed()
Application -> RefWatcher: watch(Activity)

@enduml